---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SystoleOS/infrastructure
    targetRevision: HEAD
    path: sealed-secrets/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SystoleOS/infrastructure
    targetRevision: HEAD
    path: argo-cd/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoworkflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SystoleOS/infrastructure
    targetRevision: HEAD
    path: argo-workflows/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SystoleOS/infrastructure
    targetRevision: HEAD
    path: workflows/testing/test1/base
  destination:
    server: https://kubernetes.default.svc
    namespace: testing
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
